version: '3'

services:
  web:
    build: .
    command: python ./src/manage.py runserver 0.0.0.0:8000 --settings=proxy_service_provider.settings.core
    volumes:
      - .:/src
    ports:
      - "8000:8000"